### ISSUE TITLE
race_condition_fix branch error

### ISSUE THREAD

**Issue by robj** [stevegraham/slanger#103]
I occasionally get this:

Pusher : Error : {"type":"PusherError","data":{"code":500,"message":"undefined method `[]' for nil:NilClass\n 
/Users/robert/dev/slanger/lib/slanger/channel.rb:21:in `from'\n
/Users/robert/dev/slanger/lib/slanger/channel.rb:26:in `unsubscribe'\n
/Users/robert/dev/slanger/lib/slanger/handler.rb:78:in `pusher_unsubscribe'\n
/Users/robert/dev/slanger/lib/slanger/handler.rb:34:in `onmessage'\n
/Users/robert/dev/slanger/lib/slanger/web_socket_server.rb:33:in `block (4 levels) in run'\n
/Users/robert/.rvm/gems/ruby-1.9.3-p0@rails31_new/gems/em-synchrony-1.0.3/lib/em-synchrony.rb:29:in `block in synchrony'"}} 

noting - this crashed the server previously, but on the race condition fix branch is just an error received back to the JS library..

**Comment by markburns** [comment]
Fixed here?
https://github.com/stevegraham/slanger/issues/114
