### ISSUE TITLE
Feature request: Expand the REST API

### ISSUE THREAD

**Issue by dwightgunning** [stevegraham/slanger#106]
Hi folks,

I'm looking at adding some functionality to my application which will involve clients requesting details about available channels and in particular listing the users connected to presence channels.

This seems pretty well supported in the Pusher service REST API but I can't see that it's (yet) implemented in Slanger. Let me know if I'm mistaken / not searching hard enough in the source?

I wanted to open the discussion and find out whether anybody is actively or considering working on the REST API?

I'm generally willing to dive in and work on this but my Ruby experience is limited. That said, if nobody else has a timeline for working on it I'll probably step up to the plate :-)

Dwight

**Comment by Stayallive** [comment]
Is there any news on this? :)

**Comment by jbcpollak** [comment]
Hi, I'm just wondering if `member_added` and `member_removed` are supported now?

**Comment by tboyko** [comment]
+1 would love `.channels` support.

**Comment by dwightgunning** [comment]
Housekeeping close.
