### ISSUE TITLE
Opening multiple pages or losing the first page causes persistent websocket connection closed error

### ISSUE THREAD

**Issue by whatsdis** [stevegraham/slanger#166]
Problem: Opening another tab of the same page or closing the original page will always throw a websocket error for the entire session until chrome browser is completely restarted.

    WebSocket connection to 'wss://slanger.myapp.com:8080/app/myapp?
    protocol=7&client=js&version=2.2.3&flash=false' failed: WebSocket is closed before the connection 
    is established.
    pusher.min.js:12 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":
    {"code":4001,"message":"Could not find app by key myapp. Perhaps you're connecting to the 
    wrong cluster."}}}

Steps to reproduce this problem:

Open a page that subscribes to pusher.

Open another tab to the same page. The websocket connection closed message appears.

Close all tabs and open a new one to the pusher page. Error persists.

Restart chrome, error no longer appears.

Environment: 
git commit: b61377ee32380785582266a2c7cf698b877ba491
Ubuntu 12.04, 
Pusher.js 2.2.3
Pusher Python Client (https://github.com/pusher/pusher_client_python)

**Comment by markburns** [comment]
Closing, can you re-open if you start using slanger again, and with more details. We should have some changes coming soon that will add some verbose logging on the server side which should help debug if it happens again
