### ISSUE TITLE
Events are fired twice

### ISSUE THREAD

**Issue by RadekHavelka** [stevegraham/slanger#171]
Hello,
  after a year or so, since I experimented first with Slanger, I restarted development with JS and PHP. I upgraded to current version of slanger, had to upgrade Ruby, mu current setup is following 

```
ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

```
redis-server &> /dev/null &
```

```
slanger --app_key somekey --secret somepwd -w 0.0.0.0:8081 -v
```
all is ok. Server is up and running.

then I have two basic pages :

HTML / JS

```javascript
var pusher = new Pusher('somekey', {wsHost: "domain", httpHost: "domain", wsPort: "8081", httpPort: "80"});
var channel = pusher.subscribe('my-channel');
  console.log('channel');
```

PHP

```php
include('Pusher.php');
$pusher = new Pusher( $app_key, $app_secret, $app_id, false, 'localhost', 4567);
$pusher->trigger( 'my-channel', 'my_event', 'hello world' );
```

whenever i visit the PHP page, ONE event is expected to be logged in HTML page. But, I'm seeing TWO events (very same) to be recieved.

in console where slanger server is running, I see them twice as well :

```
[[:sending_frame,
  :text,
  "{\"event\":\"my_event\",\"data\":\"\\\"hello world\\\"\",\"channel\":\"my-channel\"}"]]

[[:sending_frame,
  :text,
  "{\"event\":\"my_event\",\"data\":\"\\\"hello world\\\"\",\"channel\":\"my-channel\"}"]]
```

the CURL in Pusher.php (current version 2.2 from https://github.com/pusher/pusher-php-server ) script is being called only once. So far, I'm out of ideas what can be wrong ?

**Comment by stevegraham** [comment]
The latest gem is not up to date with the latest code in master. Try cloning the repo, doing a bundle install then, running bin/slanger with your arguments.

**Comment by RadekHavelka** [comment]
I did that, but I still see two events being sent :(

**Comment by RadekHavelka** [comment]
well, for some reason, calling the CURL from Pusher.php via php 5.3.3 makes the call twice, while doing it via php 5.6 works as expected and doing just one call ... I had the problem with literally ANY WS library i tested before finding out. So for others to know ... :)
