### ISSUE TITLE
Random Disconnects with Error code 1006

### ISSUE THREAD

**Issue by manishval** [stevegraham/slanger#177]
I have setup a load balancer in front of 8 slanger nodes and currently we're experiencing random disconnects. The console log has the following error:

```Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}```

This is what Pusher says about this error code: 

> When a WebSocket connection is closed without a "close frame", the pusher-js library emits an error with code 1006. Usually this is caused by WebSocket-incompatible proxies, which can't close the connection in the correct way.

> See: https://developer.mozilla.org/en-US/docs/WebSockets/WebSockets_reference

> How does pusher-js deal with such scenarios?

> Pusher's JavaScript client uses two strategies to maintain a working connection.

> Lower the heartbeat interval

> A "Heartbeat" is a small message that is exchanged by clients and servers to check whether connections are still open and working.

> Some proxies might terminate connections because there isn't any data sent in either direction. To counteract such behaviour, after getting an 1006 close code, the heartbeat interval is lowered to half the lifespan of the last connection (minimum 10s, maximum 120s).

> This way, connections are kept active all the time and proxies might stop disconnecting them.

> Disable WebSockets

> When pusher-js detects that two WebSocket connections failed after less than a few minutes, it decides to disable WebSocket-based transports (including Flash) and fall back to HTTP. This way clients won't waste any more time trying to use a broken transport. Additionally, pusher-js remembers last successful transport, so after refreshing the page, it will jump straight to the HTTP fallback.

I still not sure how to sort this out and I'm still looking into it. Do you guys know what could be causing this and how to fix it?

**Comment by manishval** [comment]
My nodes are averaging 20% CPU. And the load balancer is showing 2.7k connections.

**Comment by Luceos** [comment]
The load balancer is acting as proxy, how did you set the load balancer up? What are those specs and configuration?

**Comment by manishval** [comment]
We figured out what was happening. Our slanger service was encoding/decoding JSON as ASCII and whenever a payload came in with a UTF-8 character it would crash the process on emit.

To solve this we started the slanger process with ```LANG=en_US.UTF-8``` env variable.
