### ISSUE TITLE
Can't install slanger

### ISSUE THREAD

**Issue by behrad** [stevegraham/slanger#179]
running `gem install slanger` I'm getting `ERROR:  Could not find a valid gem 'slanger' (>= 0) in any repository`, I'm not a ruby developer... What could I be missing?

**Comment by markburns** [comment]
Not sure, it should just work. Might there be any reason you can't reach 
https://rubygems.org/gems/slanger. A proxy? Some kind of network restriction, etc?

If not, maybe you were just unlucky and rubygems happened to be down.
I've probably installed thousands of gems and not run into this issue.

Closing as not related to slanger itself, hopefully you can find a solution, but not sure I can help more than that.

**Comment by behrad** [comment]
a network problem,  @markburns thank you, resolved ;)
I have another question that I'd may ask here not to create another issue for it.

Does pusher (and slanger as a clone) guarantee event delivery? i.e. when app reconnects does it receive pushed event's of when it was offline?

**Comment by markburns** [comment]
No problem, glad you sorted it.

Slanger doesn't and I've not looked at pusher in a while but it doesn't
make sense IMHO that they would.
You might want to look at queues and messaging based systems if that's one
of your criteria.
