### ISSUE TITLE
multiple app?

### ISSUE THREAD

**Issue by funsterisdafunniest** [stevegraham/slanger#180]
hi, i'm sorry if this seems like a stupid question, but is there any way to make slanger works and registered in multiple apps? (just like the original pusher)

since i am planning to use this across multiple JEE apps that i have in my office and i want them to be in separate apps rather than in separate channels

**Comment by markburns** [comment]
Not at the moment but I'd be happy to see a pull request.
Obviously you could work around it with multiple slanger instances on
different ports

**Comment by funsterisdafunniest** [comment]
@markburns thanks! for now i'll just do it like as you said (with multiple instance). but when i have learned ruby quite some more, i'll be glad to add it.
