### ISSUE TITLE
Triggered event is not binding in the rails view

### ISSUE THREAD

**Issue by madhusudhan518** [stevegraham/slanger#188]
i triggered an event 

```ruby
Pusher.trigger(@my_channel, 'new-message', {:from => current_user.name, :subject => @chat_message.content, :time => Time.now.strftime("%I:%M%p"), :user_id => current_user.id})
```
binding the event in view

```erb
Pusher.host="x.x.x.x"
Pusher.ws_port=8080
Pusher.wss_port=8080
Pusher.channel_auth_endpoint="<%= pusher_auth_path %>";
```
```javascript
  var pusher = new Pusher('xxxxxxxxxxxxxxxxfcc7',
  {host: 'x.x.x.x',
  wsHost: "x.x.x.x",
  wsPort: "8080",
  encrypted: false,
  enabledTransports: ['ws', 'flash'],
});

var channel = pusher.subscribe('<%=  @my_channel %>');

channel.bind('new-message', function(data) {
  console.log("new  message bind");
});
```
but the 'new-message' event is not binding.

i am runnig slanger with -v flag, i am not getting any thing in slanger verbose when the event trigger.
can anyone tell me why this is happening ?
please help i am struck from two days.

**Comment by markburns** [comment]
What are you doing for the auth?

**Comment by madhusudhan518** [comment]
In Pusher controller 
def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        :user_id => current_user.id, # => required
        :user_info => { # => optional - for example
          :name => current_user.name,
          :email => current_user.email
        }
        })
        render :json => response
      else
        render :text => "Forbidden", :status => '403'
      end
    end

thats it.

**Comment by markburns** [comment]
I can't spot anything obviously wrong. If you can create a repo that replicates the problem I can take a look at it

**Comment by madhusudhan518** [comment]
Thank you @markburns , 
i solved it by adding pusher.port = 4567
 before pusher trigger.
