### ISSUE TITLE
Issue with socket.id in combination with Pusher gem

### ISSUE THREAD

**Issue by rogerheykoop** [stevegraham/slanger#191]
Slanger gives back socket.id's as a SecureRandom.uuid. 

The 0.14.5 version of the Pusher gem tries to validate the socket.id with this code:
      unless socket_id && /\A\d+\.\d+\z/.match(socket_id)

I suggest to change the socket.id format from a uuid to one that satisfies the socket_id format used by the pusher gem.

**Comment by Juanmcuello** [comment]
I think #186 takes care of that. See also #185.

**Comment by rogerheykoop** [comment]
You're right, its solved. Thanks.
