### ISSUE TITLE
Invalid HTTP header Error

### ISSUE THREAD

**Issue by daande** [stevegraham/slanger#200]
I am getting this in the logs when trying to connect using the pusher js client:
```
[[:initialize]]

[[:receive_data,
  "\x16\x03\x01\x00\x9B\x01\x00\x00\x97\x03\x01ME\xEB)\xF4W\x84<\xC6\x04dey\xBF\xA1\xD6\a\e\x86A\xC48\xBDg\x8B\x947x\xEE\x83\x12\xAB\x00\x00\x1C\xC0\n\xC0\x14\x009\xC0\t\xC0\x13\x003\xC0\a\xC0\x11\x005\x00/\x00\x05\x00\x04\x00\nV\x00\x01\x00\x00R\xFF\x01\x00\x01\x00\x00\x00\x00\x1C\x00\x1A\x00\x00\x17slanger.prophetcloud.io\x00\x17\x00\x00\x00#\x00\x00\x00\x05\x00\x05\x01\x00\x00\x00\x003t\x00\x00\x00\x12\x00\x00uP\x00\x00\x00\v\x00\x02\x01\x00\x00\n\x00\x06\x00\x04\x00\x17\x00\x18"]]

[[:error,
  #<EventMachine::WebSocket::HandshakeError: Invalid HTTP header: Could not parse data entirely (0 != 160)>]]

[[:unbind, :connection]]
```

On the client in the console I have logging enabled and see this:

```
Pusher : State changed : initialized -> connecting
dashboards:171 Pusher : Connecting : {"transport":"ws","url":"wss://<removed ip>:8080/app/<removed key>?protocol=7&client=js&version=3.0.0&flash=false"}
WebSocket connection to 'wss://<ip removed>/app/<key removed>?protocol=7&client=js&version=3.0.0&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```

Any ideas?

**Comment by markburns** [comment]
The latest Pusher JS client has probably drifted away from the implementation that worked with Slanger. 
When the new version of Slanger comes out we will consider any incompatibility with the latest Pusher libraries to be a bug. But for now please try the version included in the examples directory.

**Comment by tboyko** [comment]
From what I can tell, the issue is that Slanger is choking on a CSP header which is being sent.

**Comment by tboyko** [comment]
Figured it out. The Pusher client forces encryption when loaded in an HTTPS environment. Setting `encrypted: false` has no effect because this flag is merely to force encryption over unencrypted connections, not vice versa. Enabling encryption on Slanger resolved the issue for me. 

For future reference, I am using Pusher JS client version 3.0.0.

**Comment by markburns** [comment]
Looks like your previous message notification got hidden in a bunch of work related notifications.
Anyway, @tboyko thanks for the info, and glad you sorted it.
