### ISSUE TITLE
Support client-sent event webhook (client_event messages)

### ISSUE THREAD

**Issue by jbcpollak** [stevegraham/slanger#201]
It seems Slanger doesn't support client_events (https://pusher.com/docs/webhooks#client_events) - I could not find a call to webhook.post for client sent events, although I'm confused because #78 implies it works.

When I tested it, I found it doesn't actually work. I'd love to implement it myself, but I'm not familiar with Ruby and don't know where to start.

**Comment by markburns** [comment]
I'd guess it is the version of the client library you are using is not
compatible with slanger.
If it's JS you could grab the version from the examples directory
If you fix your issue a documentation improvement PR would be appreciated

**Comment by jbcpollak** [comment]
I'm using the pusher official client side library. I'll take a look at the
examples, but it doesn't look to me like slanger makes webhook calls for
client side events, it just seems to forward them to other clients.

**Comment by markburns** [comment]
Right got you. No it doesn't do a webhook post after receiving a client event. If this is something pusher supports we'd accept a pull request. You may be able to figure it out by copying the pattern from elsewhere that we do that. If you get that far I can help you understand how to test it.
Otherwise this will only get into the elixir rewrite ETA unknown.
Closing because if this continues it can be as a separate pull request.

**Comment by jbcpollak** [comment]
Ok, I'll take a look

**Comment by jbcpollak** [comment]
To clarify, yes this is something pusher supports. It sends a message like this to the server via webhook:

```
{
  "time_ms": 1454039974515,
  "events": [
    {
      "name": "client_event",
      "channel": "private-channel1",
      "event": "client-eventName",
      "data": "jsonStringifiedData",
      "socket_id": "163304.877140"
    }
  ]
}
```

It seems like the right place to put this functionality would be here:

```
    # Send a client event to the EventMachine channel.
    # Only events to channels requiring authentication (private or presence)
    # are accepted. Public channels only get events from the API.
    def send_client_message(message)
      Slanger::Redis.publish(message['channel'], Oj.dump(message, mode: :compat)) if authenticated?
    end

    # Send an event received from Redis to the EventMachine channel
    # which will send it to subscribed clients.
    def dispatch(message, channel)
      push(Oj.dump(message, mode: :compat)) unless channel =~ /\Aslanger:/
    end
```

It seems like adding a line like this to dispatch() would solve this, but I could be way off. Again, I don't know ruby so I might be misunderstanding how this works:

```
    # Send an event received from Redis to the EventMachine channel
    # which will send it to subscribed clients.
    def dispatch(message, channel)
      push(Oj.dump(message, mode: :compat)) unless channel =~ /\Aslanger:/
      # assemble payload here
      Slanger::Webhook.post payload
    end
```

If you think I'm on the right track I'll try and assemble the payload object.

**Comment by markburns** [comment]
Exactly that's right. (Based on memory and reading this email on my phone)
Try and get it working locally then have a look at the tests for the other
webhooks. Remember to restart the slanger server in between edits.
Once you've seen it working on your webhook receiving server, it shouldn't
be much more work to get tests around it.
I'd normally advocate writing the tests first but without a familiarity
with ruby and particularly testing evented code, I'd say that's a bit too
much of a learning curve to expect a good first pull request.

See how you get on. I'd like to see a pull request next too, as email based
code review/tutoring is probably not the most efficient workflow :)

**Comment by jbcpollak** [comment]
I'm familiar with the general development process, just not Ruby. I'll take
a look at the tests and see if I can make new ones.

I'm just not sure how to actually _run_ the code.

**Comment by markburns** [comment]
Not sure if by code you mean tests or the server itself.

It sounds like you know how to start the server.

bundle exec rspec


^ For tests, google for any further help with issues getting rspec to run

**Comment by jbcpollak** [comment]
Thanks, I'll give it a shot
