### ISSUE TITLE
Do not require bundler/setup in executable

### ISSUE THREAD

**Issue by svenfuchs** [stevegraham/slanger#203]
https://github.com/stevegraham/slanger/blob/master/bin/slanger#L5

This line makes it so that the instructions (`gem install slanger; slanger [...]`) from the readme won't work anywhere outside the context of this repository. It also assumes that `bundle install` has been run.

If for development purposes using bundler is useful here then the local executable can be run using `bundle exec ./bin/slanger` instead.

I'd suggest to remove this line, which should make the binary usable in any context with just `gem install slanger`, and without having to clone the repository.

**Comment by markburns** [comment]
Makes sense. PR?

**Comment by svenfuchs** [comment]
@markburns see https://github.com/stevegraham/slanger/pull/204

**Comment by markburns** [comment]
Thanks! Fixed by #204
