### ISSUE TITLE
Slanger not sending events received through Rest API

### ISSUE THREAD

**Issue by KarlJakober** [stevegraham/slanger#210]
Hello! I have used your application numerous times in the past, but for some reason this installation is giving me issues.
I am triggering an event through node, and i know slanger is receiving it because it shows up when i monitor redis. however, slanger does not relay this event to the client. I have not seen this before
Do you have any idea how I could go about debugging this?

Thank you!

![screenshot from 2016-05-06 21 32 50](https://cloud.githubusercontent.com/assets/140006/15087114/76c1ef8e-13d5-11e6-8a64-aa57e407df9a.png)

**Comment by KarlJakober** [comment]
Apparently slanger doesnt emit if there is nothing listening. derp.

**Comment by Revyn112** [comment]
I have the same error on a fresh install. How did you solved the problem?

**Comment by KarlJakober** [comment]
Just ensure you have redis running on your slanger server and ensure some pusher client is listening.
