### ISSUE TITLE
Replace em-hiredis-0.2.0 with em-hiredis-0.3.1

### ISSUE THREAD

**Issue by oklas** [stevegraham/slanger#219]
Hi!

What about upgrade em-hiredis to 0.3.1? The test seems passed.

It will be very fine.

**Comment by daveteu** [comment]
I have em-hiredis-0.3.1 but it returns error when running slanger. How do i fix this?

`WARNING: could not load hiredis extension, using (slower) pure Ruby implementation.`

**Comment by oklas** [comment]
Are you install this gem or configure slanger bundle to use this gem?

**Comment by oklas** [comment]
This task is duplicate #213. So close.
The news about update gem (or branch to use from repo) and other refer #213.
